version: "3.3"
services:
  web:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - /root/abc/inputdata:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
